#VERSION 20
# Enable this if you want the durability to be reduced for each broken block
useDurabilityPerBlock: false

#Define radius and deep
Radius: 1
Deep: 0

# These define the blocks that can be mined by the hammer, and which quality of base pickaxe is needed
# (these are set according to the information on the minecraft wiki)
Minable:
  - COBBLESTONE: [ any ]
  - STONE: [ any ]
  - STONE_BRICKS: [ any ]
  - END_STONE: [ any ]
  - BRICK: [ any ]
  - MOSSY_COBBLESTONE: [ any ]
  - COAL_ORE: [ any ]
  - SANDSTONE: [ any ]
  - END_STONE_BRICKS: [ any ]
  - NETHERRACK: [ any ]
  - NETHER_BRICKS: [ any ]
  - GRANITE: [ any ]
  - ANDESITE: [ any ]
  - DIORITE: [ any ]
  - NETHER_QUARTZ_ORE: [ any ]
  - STAINED_CLAY: [ any ]
  - HARD_CLAY: [ any ]
  - GLOWSTONE: [ any ]
  - TERRACOTTA: [ any ]
  - WHITE_TERRACOTTA: [ any ]
  - ORANGE_TERRACOTTA: [ any ]
  - MAGENTA_TERRACOTTA: [ any ]
  - LIGHT_BLUE_TERRACOTTA: [ any ]
  - YELLOW_TERRACOTTA: [ any ]
  - LIME_TERRACOTTA: [ any ]
  - PINK_TERRACOTTA: [ any ]
  - GRAY_TERRACOTTA: [ any ]
  - LIGHT_GRAY_TERRACOTTA: [ any ]
  - CYAN_TERRACOTTA: [ any ]
  - PURPLE_TERRACOTTA: [ any ]
  - BLUE_TERRACOTTA: [ any ]
  - BROWN_TERRACOTTA: [ any ]
  - GREEN_TERRACOTTA: [ any ]
  - RED_TERRACOTTA: [ any ]
  - BLACK_TERRACOTTA: [ any ]
  - LIGHT_BLUE_CONCRETE: [ any ]
  - YELLOW_CONCRETE: [ any ]
  - LIME_CONCRETE: [ any ]
  - PINK_CONCRETE: [ any ]
  - GRAY_CONCRETE: [ any ]
  - LIGHT_GRAY_CONCRETE: [ any ]
  - CYAN_CONCRETE: [ any ]
  - PURPLE_CONCRETE: [ any ]
  - BLUE_CONCRETE: [ any ]
  - BROWN_CONCRETE: [ any ]
  - GREEN_CONCRETE: [ any ]
  - RED_CONCRETE: [ any ]
  - BLACK_CONCRETE: [ any ]
  - WARPED_NYLIUM: [ any ]
  - CUT_SANDSTONE: [ any ]
  - PURPUR_BLOCK: [ any ]
  - DARK_PRISMARINE: [ any ]
  - CUT_RED_SANDSTONE: [ any ]
  - SANDSTONE: [ any ]
  - RED_SANDSTONE: [ any ]
  - PRISMARINE_BRICKS: [ any ]
  - CRIMSON_NYLIUM: [ any ]
  - BLACKSTONE: [ any ]
  - FROSTED_ICE: [ any ]
  - BLUE_ICE: [ any ]
  - PACKED_ICE: [ any ]
  - BASALT: [ any ]
  - MAGMA_BLOCK: [ any ]
  - PURPUR_PILLAR: [ any ]
  - REDSTONE_ORE: [ IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE ]
  - GLOWING_REDSTONE_ORE: [ IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE ]
  - GOLD_ORE: [ IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE ]
  - NETHER_GOLD_ORE: [ IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE ]
  - DIAMOND_ORE: [ IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE ]
  - OBSIDIAN: [ DIAMOND_PICKAXE, NETHERITE_PICKAXE ]
  - ANCIENT_DEBRIS: [ DIAMOND_PICKAXE, NETHERITE_PICKAXE ]
  - EMERALD_ORE: [ IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE ]
  - LAPIS_ORE: [ STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE ]
  - IRON_ORE: [ STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE ]
#- IRON_BLOCK: [STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE]
#- GOLD_BLOCK: [IRON_PICKAXE, DIAMOND_PICKAXE]
#- DIAMOND_BLOCK: [IRON_PICKAXE, DIAMOND_PICKAXE]

# These define the blocks that can be dug by the excavator
Diggable:
  - GRASS_BLOCK
  - DIRT
  - SAND
  - GRAVEL
  - CLAY
  - SOUL_SOIL
  - SOUL_SAND
  - GRASS_PATH
  - SNOW_BLOW
  - SNOW
  - SNOW_BLOCK
  - MYCELIUM
  - RED_SAND
  - WARPED_WART_BLOCK
  - FARMLAND
  - GLOWSTONE

#- Recipes
# |1|2|3|
# |4|5|6|
# |7|8|9|
# - TOOL_NAME: [1, 2, 3, 4, 5, 6, 7, 8, 9]
# Each number refers to a crafting table slot
# Accepted items are in the format ITEMNAME*AMOUNT. Ex: STONE*6
# EMPTY it's an empty slot, obviously
Recipes:
  #Hammers
  - WOODEN_HAMMER: [ EMPTY, OAK_LOG*1, EMPTY,
                     OAK_LOG*1, WOODEN_PICKAXE*1, OAK_LOG*1,
                     EMPTY, OAK_LOG*1, EMPTY ]

  - STONE_HAMMER: [ EMPTY, STONE*1, EMPTY,
                    STONE*1, STONE_PICKAXE*1, STONE*1,
                    EMPTY, STONE*1, EMPTY ]

  - IRON_HAMMER: [ EMPTY, IRON_INGOT*1, EMPTY,
                   IRON_INGOT*1, IRON_PICKAXE*1, IRON_INGOT*1,
                   EMPTY, IRON_INGOT*1, EMPTY ]

  - GOLDEN_HAMMER: [ EMPTY, GOLD_INGOT*1, EMPTY,
                     GOLD_INGOT*1, GOLDEN_PICKAXE*1, GOLD_INGOT*1,
                     EMPTY, GOLD_INGOT*1, EMPTY ]

  - DIAMOND_HAMMER: [ EMPTY, DIAMOND*1, EMPTY,
                      DIAMOND*1, DIAMOND_PICKAXE*1, DIAMOND*1,
                      EMPTY, DIAMOND*1, EMPTY ]

  - NETHERITE_HAMMER: [ EMPTY, NETHERITE_INGOT*1, EMPTY,
                        NETHERITE_INGOT*1, NETHERITE_PICKAXE*1, NETHERITE_INGOT*1,
                        EMPTY, NETHERITE_INGOT*1, EMPTY ]

  #Excavators
  - WOODEN_EXCAVATOR: [ EMPTY, OAK_LOG*1, EMPTY,
                        OAK_LOG*1, WOODEN_SHOVEL*1, OAK_LOG*1,
                        EMPTY, OAK_LOG*1, EMPTY ]

  - STONE_EXCAVATOR: [ EMPTY, STONE*1, EMPTY,
                       STONE*1, STONE_SHOVEL*1, STONE*1,
                       EMPTY, STONE*1, EMPTY ]

  - IRON_EXCAVATOR: [ EMPTY, IRON_INGOT*1, EMPTY,
                      IRON_INGOT*1, IRON_SHOVEL*1, IRON_INGOT*1,
                      EMPTY, IRON_INGOT*1, EMPTY ]

  - GOLDEN_EXCAVATOR: [ EMPTY, GOLD_INGOT*1, EMPTY,
                        GOLD_INGOT*1, GOLDEN_SHOVEL*1, GOLD_INGOT*1,
                        EMPTY, GOLD_INGOT*1, EMPTY ]

  - DIAMOND_EXCAVATOR: [ EMPTY, DIAMOND*1, EMPTY,
                         DIAMOND*1, DIAMOND_SHOVEL*1, DIAMOND*1,
                         EMPTY, DIAMOND*1, EMPTY ]

  - NETHERITE_EXCAVATOR: [ EMPTY, NETHERITE_INGOT*1, EMPTY,
                           NETHERITE_INGOT*1, NETHERITE_SHOVEL*1, NETHERITE_INGOT*1,
                           EMPTY, NETHERITE_INGOT*1, EMPTY ]

  #Plows
  - WOODEN_PLOW: [ EMPTY, OAK_LOG*1, EMPTY,
                   OAK_LOG*1, WOODEN_HOE*1, OAK_LOG*1,
                   EMPTY, OAK_LOG*1, EMPTY ]

  - STONE_PLOW: [ EMPTY, STONE*1, EMPTY,
                  STONE*1, STONE_HOE*1, STONE*1,
                  EMPTY, STONE*1, EMPTY ]

  - IRON_PLOW: [ EMPTY, IRON_INGOT*1, EMPTY,
                 IRON_INGOT*1, IRON_HOE*1, IRON_INGOT*1,
                 EMPTY, IRON_INGOT*1, EMPTY ]

  - GOLDEN_PLOW: [ EMPTY, GOLD_INGOT*1, EMPTY,
                   GOLD_INGOT*1, GOLDEN_HOE*1, GOLD_INGOT*1,
                   EMPTY, GOLD_INGOT*1, EMPTY ]

  - DIAMOND_PLOW: [ EMPTY, DIAMOND*1, EMPTY,
                    DIAMOND*1, DIAMOND_HOE*1, DIAMOND*1,
                    EMPTY, DIAMOND*1, EMPTY ]

  - NETHERITE_PLOW: [ EMPTY, NETHERITE_INGOT*1, EMPTY,
                      NETHERITE_INGOT*1, NETHERITE_HOE*1, NETHERITE_INGOT*1,
                      EMPTY, NETHERITE_INGOT*1, EMPTY ]
