# Enable this if you want the durability to be reduced for each broken block
useDurabilityPerBlock: false

# These define the blocks that can be mined by the hammer, and which quality of base pickaxe is needed
# (these are set according to the information on the minecraft wiki)
Minable:
- COBBLESTONE: [any]
- STONE: [any]
- STONE_BRICKS: [any]
- END_STONE: [any]
- BRICK: [any]
- MOSSY_COBBLESTONE: [any]
- COAL_ORE: [any]
- SANDSTONE: [any]
- END_STONE_BRICKS: [any]
- NETHERRACK: [any]
- NETHER_BRICKS: [any]
- GRANITE: [any]
- ANDESITE: [any]
- DIORITE:  [any]
- NETHER_QUARTZ_ORE: [any]
- STAINED_CLAY: [any]
- HARD_CLAY: [any]
- GLOWSTONE: [any]
- TERRACOTTA: [any]
- WHITE_TERRACOTTA: [any]
- ORANGE_TERRACOTTA: [any]
- MAGENTA_TERRACOTTA: [any]
- LIGHT_BLUE_TERRACOTTA: [any]
- YELLOW_TERRACOTTA: [any]
- LIME_TERRACOTTA: [any]
- PINK_TERRACOTTA: [any]
- GRAY_TERRACOTTA: [any]
- LIGHT_GRAY_TERRACOTTA: [any]
- CYAN_TERRACOTTA: [any]
- PURPLE_TERRACOTTA: [any]
- BLUE_TERRACOTTA: [any]
- BROWN_TERRACOTTA: [any]
- GREEN_TERRACOTTA: [any]
- RED_TERRACOTTA: [any]
- BLACK_TERRACOTTA: [any]
- LIGHT_BLUE_CONCRETE: [any]
- YELLOW_CONCRETE: [any]
- LIME_CONCRETE: [any]
- PINK_CONCRETE: [any]
- GRAY_CONCRETE: [any]
- LIGHT_GRAY_CONCRETE: [any]
- CYAN_CONCRETE: [any]
- PURPLE_CONCRETE: [any]
- BLUE_CONCRETE: [any]
- BROWN_CONCRETE: [any]
- GREEN_CONCRETE: [any]
- RED_CONCRETE: [any]
- BLACK_CONCRETE: [any]
- WARPED_NYLIUM: [any]
- CUT_SANDSTONE: [any]
- PURPUR_BLOCK: [any]
- DARK_PRISMARINE: [any]
- CUT_RED_SANDSTONE: [any]
- SANDSTONE: [any]
- RED_SANDSTONE: [any]
- PRISMARINE_BRICKS: [any]
- CRIMSON_NYLIUM: [any]
- BLACKSTONE: [any]
- FROSTED_ICE: [any]
- BLUE_ICE: [any]
- PACKED_ICE: [any]
- BASALT: [any]
- MAGMA_BLOCK: [any]
- PURPUR_PILLAR: [any]
- REDSTONE_ORE: [IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
- GLOWING_REDSTONE_ORE: [IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
- GOLD_ORE: [IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
- NETHER_GOLD_ORE: [IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
- DIAMOND_ORE: [IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
- OBSIDIAN: [DIAMOND_PICKAXE, NETHERITE_PICKAXE]
- ANCIENT_DEBRIS: [DIAMOND_PICKAXE, NETHERITE_PICKAXE]
- EMERALD_ORE: [IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
- LAPIS_ORE: [STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
- IRON_ORE: [STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE, NETHERITE_PICKAXE]
#- IRON_BLOCK: [STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE]
#- GOLD_BLOCK: [IRON_PICKAXE, DIAMOND_PICKAXE]
#- DIAMOND_BLOCK: [IRON_PICKAXE, DIAMOND_PICKAXE]

# These define the blocks that can be dug by the excavator
Diggable:
 - GRASS_BLOCK
 - DIRT
 - SAND
 - GRAVEL
 - CLAY
 - SOUL_SOIL
 - SOUL_SAND
 - GRASS_PATH
 - SNOW_BLOW
 - SNOW
 - SNOW_BLOCK
 - MYCELIUM
 - RED_SAND
 - WARPED_WART_BLOCK
 - FARMLAND
 - GLOWSTONE